
# get user by id
GET http://localhost:3333/users/24
###


# get user by nickname
GET http://127.0.0.1:3333/users/nick/?nickname=Mari

###


# get all users
GET http://localhost:3333/users/
###


# create new user
POST http://localhost:3333/users/
content-type: application/json

{
	"nickname": "John Doe"
}
###

# update user
PUT http://localhost:3333/users/24
content-type: application/json

{
    "nickname": "john Doidão"
}

###
PUT http://localhost:3333/users/24
content-type: application/json

{

}

###

DELETE http://localhost:3333/users/36
###
