

GET http://localhost:3333/users/3
###

GET http://localhost:3333/users/
###

POST http://localhost:3333/users/
content-type: application/json

{
	"name": "John Doe",
    "email": "johnDoe@gmail.com"
}
###

PUT http://localhost:3333/users/1
content-type: application/json

{
	"name": "Tom Roe",
    "email": "tomRoe@gmail.com"
}
###

PUT http://localhost:3333/users/2
content-type: application/json

{
    "email": "johnDoidão@gmail.com"
}

###
PUT http://localhost:3333/users/1
content-type: application/json

{

}
###

DELETE http://localhost:3333/users/3
###


