

GET http://localhost:3333/users/9
###

GET http://localhost:3333/users/
###


POST http://localhost:3333/users/
content-type: application/json

{
	"name": "John Doe",
    "email": "johnDoe@gmail.com"
}
###

DELETE http://localhost:3333/users/11
###